services:
  app:
    build: .
    image: narsapi:latest
    container_name: narsapi
    command: ["gunicorn", "-w", "3", "-b", "0.0.0.0:5000", "api:create_app()"]
    ports:
      - 5000:5000
    volumes:
      - .:/app
