services:
    app:
      build: .
      image: nrsa:latest
      environment:
        - FLASK_APP=api
        - FLASK_ENV=development
        - PYTHONUNBUFFERED=1
      container_name: nars
      command: flask run --host 0.0.0.0 --port 5000
      ports:
        - 5000:5000
      volumes:
        - .:/app
